version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8080:8080"

  crawler:
    build: ./crawler

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=...
#      - MONGO_INITDB_ROOT_PASSWORD=...

volumes:
  mongodb_data:
