version: '3.8'

services:
  api:
    build:
      context: crawler
      dockerfile: ../Dockerfile.api
    env_file:
      local.env
    ports:
      - "8080:8080"

  crawler:
    build:
      context: crawler
      dockerfile: ../Dockerfile.crawler
    env_file:
      local.env

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=...
#      - MONGO_INITDB_ROOT_PASSWORD=...

volumes:
  mongodb_data:
