name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push api
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:crawler-api


  crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push crawler
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.crawler
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:crawler-crawler

  deploy:
    runs-on: ubuntu-latest
    needs:
      - api
      - crawler

    steps:
      - name: Deploy via ssh
        uses: appleboy/ssh-action@master
        env:
          MONGO_HOST: "api.christof-schramm.net"
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        with:
          host: api.christof-schramm.net
          username: ${{ secrets.SSH_SERVER_USERNAME }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          envs: MONGO_USER,MONGO_HOST,MONGO_PASSWORD
          script: |
            docker container prune -f
            docker image prune -f

            docker pull schrammc012/schrammc-playground:crawler-crawler
            docker pull schrammc012/schrammc-playground:crawler-api

            docker stop crawler-container || true
            docker stop api-container || true

            docker rm crawler-container || true
            docker rm api-container || true

            docker run -e "MONGO_HOST=$MONGO_HOST" -e "MONGO_USER=$MONGO_USER" -e "MONGO_PASSWORD=$MONGO_PASSWORD" -d --name crawler-container schrammc012/schrammc-playground:crawler-crawler
            docker run -e "MONGO_HOST=$MONGO_HOST" -e "MONGO_USER=$MONGO_USER" -e "MONGO_PASSWORD=$MONGO_PASSWORD" -d --name api-container -p 80:8080 schrammc012/schrammc-playground:crawler-api

